/* Test data for project table */
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project1', 'This is a description', '01/06/2023', '01/06/2024', 'To do');
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project2', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '01/01/2023', '20/08/2025', 'In progress');
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project3', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '05/05/2021', '01/01/2022', 'Done');
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project4', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '08/01/2024', '08/01/2025', 'To do');
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project5', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '26/05/2023', '20/06/2024', 'Paused');
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project6', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '01/03/2020', '25/04/2027', 'In progress');
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project7', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '05/09/2021', '24/12/2025', 'In progress');
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project8', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '01/01/2019', '01/03/2026', 'Paused');
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project9', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '31/12/2020', '31/12/2021', 'Done');
INSERT INTO `calendue`.`project` (`project_name`, `project_description`, `project_start`, `project_deadline`, `project_status`) VALUES ('Project10', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '22/04/2022', '25/05/2022', 'In progress');

/* Test data for subproject table */
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('1', 'Subproject1', 'This is a subproject description', '03/05/2024', 'To do');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('1', 'Subproject2', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '01/02/2024', 'To do');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('1', 'Subproject3', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '15/10/2023', 'In progress');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('1', 'Subproject4', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '20/08/2023', 'In progress');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('1', 'Subproject5', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '30/09/2023', 'Paused');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('1', 'Subproject6', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '09/04/2024', 'Paused');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('1', 'Subproject7', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '17/07/2023', 'Done');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('2', 'Subproject8', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '04/03/2024', 'To do');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('2', 'Subproject9', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '19/05/2025', 'To do');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('2', 'Subproject10', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '30/07/2025', 'To do');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('2', 'Subproject11', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '07/11/2023', 'In progress');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('2', 'Subproject12', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '11/12/2023', 'In progress');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('2', 'Subproject13', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '14/05/2023', 'Done');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('3', 'Subproject14', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '30/11/2021', 'Done');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('4', 'Subproject15', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '27/10/2024', 'To do');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('4', 'Subproject16', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '10/11/2024', 'To do');
INSERT INTO `calendue`.`subproject` (`project_id`, `subproject_name`, `subproject_description`, `subproject_deadline`, `subproject_status`) VALUES ('4', 'Subproject17', 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima.', '02/01/2025', 'To do');

/* Test data for task table*/
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_comment`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task1', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', 'This is a comment', '20/01/2024', '2', '1', 'In progress');
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_comment`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task2', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', 'This is a comment', '15/01/2024', '5', '4', 'Paused');
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_comment`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task3', NULL, NULL, '10/01/2024', '1', '2', 'In progress');
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task4', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '5/01/2024', '3', '2', 'Paused');
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task5', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '1/01/2024', '4', '1', 'In progress');
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task6', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '20/12/2023', '1', '4', 'Inprogress');
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task7', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '10/12/2023', '2', '3', 'Done');
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task8', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '05/12/2023', '10', '1', 'Done');
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task9', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '01/12/2023', '22', '1', 'In progress');
INSERT INTO `calendue`.`task` (`subproject_id`, `task_name`, `task_description`, `task_deadline`, `task_hours`, `task_priority`, `task_status`) VALUES ('1', 'Task10', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.', '20/11/2023', '5', '4', 'To do');

/*Test data for user table*/
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user@email.kea', '1', 'User Usersen');
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user2', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user2@email.kea', '0', 'Ben Bensen');
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user3', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user3@email.kea', '0', 'Adam Adamsen');
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user4', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user4@email.kea', '0', 'Lone Lonesen');
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user5', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user5@email.kea', '0', 'Kim Kimsen');
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user6', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user6@email.kea', '0', 'Karen Karensen');
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user7', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user7@email.kea', '0', 'Hans Hansen');
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user8', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user8@email.kea', '0', 'Simone Simonesen');
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user9', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user9@email.kea', '0', 'Lars Larsen');
INSERT INTO `calendue`.`user` (`username`, `password`, `email`, `is_admin`, `full_name`) VALUES ('user10', '$2a$10$rK3VO4Xd8cYNs0X6qsCWCuKSPEspK4xkEeXAr3rLjOEY1Xwayr9jS', 'user10@email.kea', '0', 'Gandalf Gandalfsen');

/* Test data for project_user table*/
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '1', 'Project Leader');
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '2', 'Project Leader');
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '3', 'Developer');
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '4', 'Developer');
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '5', 'Developer');
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '6', 'Developer');
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '7', 'Developer');
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '8', 'Developer');
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '9', 'Developer');
INSERT INTO `calendue`.`project_user` (`project_id`, `user_id`, `role`) VALUES ('1', '10', 'Developer');

/* Test data for task_user table*/
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('1', '10');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('1', '7');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('1', '3');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('1', '5');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('2', '4');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('2', '9');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('3', '6');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('4', '1');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('4', '8');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('4', '2');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('4', '10');
INSERT INTO `calendue`.`task_user` (`task_id`, `user_id`) VALUES ('5', '1');